<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="RDPC42" failures="8" tests="23" name="Test" time="14.628" errors="0" timestamp="2023-05-31T18:08:18 IST">
  <testcase classname="api.test.LoginTests" name="testLogin" time="5.346"/>
  <testcase classname="api.test.LoginTests" name="testResendOtp" time="0.493"/>
  <testcase classname="api.test.LoginTests" name="testVerifyOtp" time="0.485"/>
  <testcase classname="api.test.PincodeServiceableTests" name="pincodeServiceable" time="0.595"/>
  <testcase classname="api.test.DetectDeviceTests" name="testDetectDevice" time="1.434"/>
  <testcase classname="api.test.ListVariantsTests" name="testListVariantQuestions" time="0.59"/>
  <testcase classname="api.test.GetCommonQuoteTests" name="testGetCommonQuotes" time="0.733"/>
  <testcase classname="api.test.GetAddressTests" name="testGetAddress" time="0.595"/>
  <testcase classname="api.test.AddUpdateAddressTests" name="testAddUpdateAddress" time="0.313"/>
  <testcase classname="api.test.ApplicablePaymentMethodsTests" name="testApplicablePaymentMethods" time="0.416"/>
  <testcase classname="api.test.VerifyIfscTests" name="testVerifyIfsc" time="0.342"/>
  <testcase classname="api.test.OrderAvailableTimeslotsTests" name="testOrderAvaialbleTimeslots" time="0.911">
    <failure type="org.json.JSONException" message="JSONObject[&amp;quot;list[0].date&amp;quot;] not found.">
      <![CDATA[org.json.JSONException: JSONObject["list[0].date"] not found.
at org.json.JSONObject.get(JSONObject.java:570)
at api.test.OrderAvailableTimeslotsTests.testOrderAvaialbleTimeslots(OrderAvailableTimeslotsTests.java:44)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testOrderAvaialbleTimeslots -->
  <testcase classname="api.test.ApplyCouponTests" name="testApplyCoupon" time="0.305"/>
  <testcase classname="api.test.ApplyCouponTests" name="testRevokeCoupon" time="0.351"/>
  <testcase classname="api.test.PlaceOrderTests" name="testPlceOrder" time="0.305">
    <failure type="java.lang.AssertionError" message="expected [200] but found [422]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [422]
at api.test.PlaceOrderTests.testPlceOrder(PlaceOrderTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testPlceOrder -->
  <testcase classname="api.test.ChangePaymentMethodTests" name="testChangePaymentMethod" time="0.012">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.ChangePaymentMethodEndPoints.changePaymentMethod(ChangePaymentMethodEndPoints.java:10)
at api.test.ChangePaymentMethodTests.testChangePaymentMethod(ChangePaymentMethodTests.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testChangePaymentMethod -->
  <testcase classname="api.test.RescheduleOrderTests" name="testRescheduleOrder" time="0.28">
    <failure type="java.lang.AssertionError" message="expected [Order has been rescheduled] but found [Invalid or missing parameters]">
      <![CDATA[java.lang.AssertionError: expected [Order has been rescheduled] but found [Invalid or missing parameters]
at api.test.RescheduleOrderTests.testRescheduleOrder(RescheduleOrderTests.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testRescheduleOrder -->
  <testcase classname="api.test.ViewProfileTests" name="testViewProfile" time="0.284"/>
  <testcase classname="api.test.CancelOrderTests" name="testCancelOrder" time="0.004">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.CancelOrderEndPoints.cancelOrder(CancelOrderEndPoints.java:10)
at api.test.CancelOrderTests.testCancelOrder(CancelOrderTests.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testCancelOrder -->
  <testcase classname="api.test.CancelOrderTests" name="testCancelSameOrder" time="0.007">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.CancelOrderEndPoints.cancelOrder(CancelOrderEndPoints.java:10)
at api.test.CancelOrderTests.testCancelSameOrder(CancelOrderTests.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testCancelSameOrder -->
  <testcase classname="api.test.ListOrdersTests" name="testListOrders" time="0.295"/>
  <testcase classname="api.test.SaveInstructionsTests" name="testSaveInstructions" time="0.243">
    <failure type="java.lang.AssertionError" message="expected [Instructions have been saved] but found [Order does not exist]">
      <![CDATA[java.lang.AssertionError: expected [Instructions have been saved] but found [Order does not exist]
at api.test.SaveInstructionsTests.testSaveInstructions(SaveInstructionsTests.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testSaveInstructions -->
  <testcase classname="api.test.OrderDetailsTests" name="testOrderDetails" time="0.005">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.OrderDetailsEndPoints.orderDeatails(OrderDetailsEndPoints.java:10)
at api.test.OrderDetailsTests.testOrderDetails(OrderDetailsTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testOrderDetails -->
</testsuite> <!-- Test -->
