<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="RDPC42" failures="9" tests="29" name="Test" time="13.531" errors="0" timestamp="2023-07-07T16:55:45 IST">
  <testcase classname="api.test.LoginTests" name="testLogin" time="4.904"/>
  <testcase classname="api.test.LoginTests" name="testResendOtp" time="0.479"/>
  <testcase classname="api.test.LoginTests" name="testVerifyOtp" time="0.35"/>
  <testcase classname="api.test.PincodeServiceableTests" name="pincodeServiceable" time="0.35"/>
  <testcase classname="api.test.DetectDeviceTests" name="testDetectDevice" time="0.88"/>
  <testcase classname="api.test.ListVariantsTests" name="testListVariantQuestions" time="0.585"/>
  <testcase classname="api.test.GetCommonQuoteTests" name="testGetCommonQuotes" time="0.406"/>
  <testcase classname="api.test.GetAddressTests" name="testGetAddress" time="0.411"/>
  <testcase classname="api.test.AddUpdateAddressTests" name="testAddUpdateAddress" time="0.307"/>
  <testcase classname="api.test.ApplicablePaymentMethodsTests" name="testApplicablePaymentMethods" time="0.415"/>
  <testcase classname="api.test.VerifyIfscTests" name="testVerifyIfsc" time="0.341"/>
  <testcase classname="api.test.OrderAvailableTimeslotsTests" name="testOrderAvaialbleTimeslots" time="0.327"/>
  <testcase classname="api.test.ApplyCouponTests" name="testApplyCoupon" time="0.301"/>
  <testcase classname="api.test.ApplyCouponTests" name="testRevokeCoupon" time="0.298"/>
  <testcase classname="api.test.PlaceOrderTests" name="testPlaceOrder" time="0.263">
    <failure type="java.lang.AssertionError" message="expected [200] but found [422]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [422]
at api.test.PlaceOrderTests.testPlaceOrder(PlaceOrderTests.java:32)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testPlaceOrder -->
  <testcase classname="api.test.ListOrdersTests" name="testListOrders" time="0.245"/>
  <testcase classname="api.test.NotificationCountTests" name="testNotificationCount" time="0.258"/>
  <testcase classname="api.test.OrderDetailsTests" name="testOrderDetails" time="0.003">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.OrderDetailsEndPoints.orderDeatails(OrderDetailsEndPoints.java:10)
at api.test.OrderDetailsTests.testOrderDetails(OrderDetailsTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testOrderDetails -->
  <testcase classname="api.test.SupportQuestionsTests" name="testSupportQuestions" time="0.341"/>
  <testcase classname="api.test.RequestCallbackTests" name="testCreateTicket" time="0.226">
    <failure type="java.lang.AssertionError" message="expected [200] but found [400]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [400]
at api.test.RequestCallbackTests.testCreateTicket(RequestCallbackTests.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- testCreateTicket -->
  <testcase classname="api.test.RequestCallbackTests" name="testAlreadyCreated" time="0.258"/>
  <testcase classname="api.test.ChangePaymentMethodTests" name="testChangePaymentMethod" time="0.004">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.ChangePaymentMethodEndPoints.changePaymentMethod(ChangePaymentMethodEndPoints.java:10)
at api.test.ChangePaymentMethodTests.testChangePaymentMethod(ChangePaymentMethodTests.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testChangePaymentMethod -->
  <testcase classname="api.test.RescheduleOrderTests" name="testRescheduleOrder" time="0.001">
    <failure type="java.lang.Error" message="Unresolved compilation problem: 
	pickup_date cannot be resolved or is not a field
">
      <![CDATA[java.lang.Error: Unresolved compilation problem: 
pickup_date cannot be resolved or is not a field

at api.endpoints.RescheduleOrderEndPoints.rescheduleOrder(RescheduleOrderEndPoints.java:19)
at api.test.RescheduleOrderTests.testRescheduleOrder(RescheduleOrderTests.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testRescheduleOrder -->
  <testcase classname="api.test.ViewProfileTests" name="testViewProfile" time="0.277"/>
  <testcase classname="api.test.UpdateProfileTests" name="testUpdateProfile" time="0.576">
    <failure type="java.lang.NumberFormatException" message="For input string: &amp;quot;Profile has been updated&amp;quot;">
      <![CDATA[java.lang.NumberFormatException: For input string: "Profile has been updated"
at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:668)
at java.base/java.lang.Short.parseShort(Short.java:137)
at java.base/java.lang.Short.parseShort(Short.java:163)
at java_lang_Short$parseShort.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
at io.restassured.internal.common.path.ObjectConverter.convertObjectTo(ObjectConverter.groovy:37)
at io.restassured.path.json.JsonPath.getShort(JsonPath.java:287)
at api.test.UpdateProfileTests.testUpdateProfile(UpdateProfileTests.java:19)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testUpdateProfile -->
  <testcase classname="api.test.CancelOrderTests" name="testCancelOrder" time="0.004">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.CancelOrderEndPoints.cancelOrder(CancelOrderEndPoints.java:10)
at api.test.CancelOrderTests.testCancelOrder(CancelOrderTests.java:15)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testCancelOrder -->
  <testcase classname="api.test.CancelOrderTests" name="testCancelSameOrder" time="0.002">
    <failure type="java.lang.ClassCastException" message="class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader &amp;apos;app&amp;apos;)">
      <![CDATA[java.lang.ClassCastException: class io.restassured.internal.RequestSpecificationImpl cannot be cast to class io.restassured.response.Response (io.restassured.internal.RequestSpecificationImpl and io.restassured.response.Response are in unnamed module of loader 'app')
at api.endpoints.CancelOrderEndPoints.cancelOrder(CancelOrderEndPoints.java:10)
at api.test.CancelOrderTests.testCancelSameOrder(CancelOrderTests.java:29)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testCancelSameOrder -->
  <testcase classname="api.test.SaveInstructionsTests" name="testSaveInstructions" time="0.267">
    <failure type="java.lang.AssertionError" message="expected [Instructions have been saved] but found [Order does not exist]">
      <![CDATA[java.lang.AssertionError: expected [Instructions have been saved] but found [Order does not exist]
at api.test.SaveInstructionsTests.testSaveInstructions(SaveInstructionsTests.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- testSaveInstructions -->
  <testcase classname="api.test.NotificationListTests" name="testNotificationList" time="0.247"/>
</testsuite> <!-- Test -->
